### PR TITLE
err was not defined before assignment

### PR DESCRIPTION
**Pull request by sbirla09**
hitting this exception while running swf in a standalone container

### CODE REVIEW

**Comment by glynn-zenefits** [comment]
:+1: but note as you probably know the you're hitting this error because of another error, normally that error is never hit in production, i.e. are you trying to make a new SWF domain or something?

**Comment by sbirla09** [comment]
not really. both the containers - yp3 and swf - are running on same machine. So, localhost for swf should have worked. There is no new domain for swf.

**Comment by sbirla09** [comment]
@glynn-zenefits  Travis CI is failing!! Can I merge it directly with CI?

**Comment by glynn-zenefits** [comment]
I don't think we use travis here, I was going to ask if you turned it on
but it might have been turned on when z-frontend repo started using Travis
(i.e. there's likely a Travis config file in this repo from before it was
forked years ago but hasn't been run since).

**Pull request merged**
